server {
    listen 80;

    # 精簡正則，同時支援 -am, -ap, -qa 等環境
    server_name ~^(?<subdomain>.+)-[1-5](am|ap)\.(?<tld>.+)$;
    server_name ~^(?<subdomain>.+?-[1-5](am|ap)-[^\.]+)\.(?<tld>.+)$;
    server_name kklo-agent-qa.gogo-lucky.com;

    index index.html;
    access_log /var/log/nginx/web_access.log main buffer=192k flush=30s;
    error_log /var/log/nginx/web_error.log;

    ## Root Location
    location / {
        add_header Device 'PC';
        root /data/agent/;

        # 乾淨且安全的 SPA 路由配置（完全避免 500 死循環）
        try_files $uri $uri/ /index.html;
    }
}
